
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF

REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
