# This Vagrant file will create a RHEL 9 VM using the libvirt provider.
# It intended to be used only for local tests.

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = "2048"
    libvirt.cpus = 2
    libvirt.default_prefix = "complytime_"
    libvirt.machine_virtual_size = 10
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.box_url  = "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-42-1.1.x86_64.vagrant.libvirt.box"
    fedora.vm.box      = "f42-cloud-base"
    fedora.vm.hostname = "fedora42"
  end

  # This will collect the SSH public key used to access the VM. Update the path if needed.
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

  # To customize the VM during its provisioning, write the commands between "-SCRIPT" and "SCRIPT".
  $bootstrap = <<-SCRIPT
  # Start the customizations
  mkdir -p /root/.ssh
  echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  echo #{ssh_pub_key} >> /root/.ssh/authorized_keys

  # Configure Ansible user that can elevate privileges without a password
  useradd -G wheel ansible && mkdir -p /home/ansible/.ssh && echo #{ssh_pub_key} >> /home/ansible/.ssh/authorized_keys
  chown -R ansible:ansible /home/ansible/.ssh && chmod 700 /home/ansible/.ssh
  chmod 600 /home/ansible/.ssh/authorized_keys
  echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible
  chmod 0440 /etc/sudoers.d/ansible

  # Ensure filesystem is resized to maximum size
  btrfs filesystem resize max /home

  # Install required packages
  dnf install -y qemu-guest-agent openssh-clients openssh-server

  # Install some useful packages
  dnf install -y git python3-pip tar tree vim -y
  dnf install -y --nobest openscap-scanner openscap-engine-sce scap-security-guide

  # Upgrade the system
  dnf upgrade -y
  SCRIPT
  config.vm.provision "shell", inline: $bootstrap

  config.trigger.after :up do |trigger|
    trigger.name = "Execute local script to update Ansible inventory and add SSH key"
    trigger.run = { inline: "../populate_ansible_inventory.sh" }
  end
end
