---
- name: "Simulates the use of main 'complyctl' features in a Fedora VM"
  hosts: demo_vm
  become: false
  vars:
    complyctl_workdir: "~/complyctl-demo"
    policy_id: cis-fedora

    # These directories are created locally to stored files fetched from testing VM
    # They can be safely removed after the tests
    local_directories:
      - "./downloads_scan1"
      - "./downloads_scan2"

    # A list of files to be fetched from testing VM after each testing phase
    generated_files:
      - ".complytime/scan/evaluation-log-*.yaml"
      - "report-*.md"
      - "assessment-results-*.json"

    # This command is used multiple times to allow easier comparison between testing phases
    cmd_tree: "tree -Dpugh --timefmt %H:%M -L2 .complytime/"

    # Variables used for fixing the system
    var_sudo_logfile: "/var/log/sudo.log"
    var_accounts_user_umask: "027"

  tasks:
    # Prep phase is used to ensure the reproducibility of this environment
    - name: "Prep - Ensure removal of 'firewalld' package to not be compliant with 'package_firewalld_installed'"
      ansible.builtin.dnf:
        name:
          - firewalld
        state: absent
      become: true

    - name: "Prep - Ensure '/etc/sudoers' is not compliant with 'sudo_custom_logfile rule'"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: 'Defaults logfile={{ var_sudo_logfile }}'
        validate: /usr/sbin/visudo -cf %s
        state: absent
      become: true

    - name: "Prep - Ensure '/etc/login.defs' is not compliant with 'accounts_umask_etc_login_defs'"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: ^(\s*)UMASK(\s+).*
        replace: '\g<1>UMASK\g<2>022'
      become: true

    - name: "Prep - Ensure local directories to fetch generated files"
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ local_directories }}"

    # Phase 1: Scanning out-of-box
    - name: "Starting the Phase 1 - Scanning out-of-box"
      ansible.builtin.debug:
        msg: "Phase 1 will execute the sequence of 'complyctl' commands out-of-box"

    - name: "Phase 1 - Execute 'generate' command to create assessment plan and policy"
      ansible.builtin.command:
        cmd: "~/bin/complyctl generate --policy-id {{ policy_id }}"
        chdir: "{{ complyctl_workdir }}"
      changed_when: true

    - name: "Phase 1 - Execute 'scan' command with pretty format"
      ansible.builtin.command:
        cmd: "~/bin/complyctl scan --policy-id {{ policy_id }} --format pretty"
        chdir: "{{ complyctl_workdir }}"
      changed_when: true
      become: true

    - name: "Phase 1 - Run tree command to collect directory structure"
      ansible.builtin.command:
        cmd: "{{ cmd_tree }}"
        chdir: "{{ complyctl_workdir }}"
      changed_when: false
      register: result_tree_scan1

    - name: "Phase 1 - Fetch files from remote host to local machine"
      ansible.builtin.shell:
        cmd: "ls {{ item }}"
        chdir: "{{ complyctl_workdir }}"
      register: phase1_files
      loop: "{{ generated_files }}"
      changed_when: false
      failed_when: false

    - name: "Phase 1 - Fetch matched files"
      ansible.builtin.fetch:
        src: "{{ complyctl_workdir }}/{{ item }}"
        dest: "{{ local_directories[0] }}/"
        flat: true
      loop: "{{ phase1_files.results | map(attribute='stdout_lines') | flatten }}"
      become: true

    # Phase 2: Fixing the failed rules and scanning again
    - name: "Starting the Phase 2 - Fixing the failed rules and scanning again"
      ansible.builtin.debug:
        msg: "Phase 2 will fix the failed rules and scan the system again"

    - name: "Phase 2 - Fix package_firewalld_installed"
      ansible.builtin.dnf:
        name:
          - firewalld
        state: present
      become: true

    - name: "Phase 2 - Fix sudo_custom_logfile"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: 'Defaults logfile={{ var_sudo_logfile }}'
        validate: /usr/sbin/visudo -cf %s
      become: true

    - name: "Phase 2 - Fix accounts_umask_etc_login_defs"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: ^(\s*)UMASK(\s+).*
        replace: '\g<1>UMASK\g<2>{{ var_accounts_user_umask }}'
      become: true

    - name: "Phase 2 - Execute 'scan' command again after fixes"
      ansible.builtin.command:
        cmd: "~/bin/complyctl scan --policy-id {{ policy_id }} --format pretty"
        chdir: "{{ complyctl_workdir }}"
      changed_when: true
      become: true

    - name: "Phase 2 - Run tree command to collect directory structure"
      ansible.builtin.command:
        cmd: "{{ cmd_tree }}"
        chdir: "{{ complyctl_workdir }}"
      changed_when: false
      register: result_tree_scan2

    - name: "Phase 2 - Fetch files from remote host to local machine"
      ansible.builtin.shell:
        cmd: "ls {{ item }}"
        chdir: "{{ complyctl_workdir }}"
      register: phase2_files
      loop: "{{ generated_files }}"
      changed_when: false
      failed_when: false

    - name: "Phase 2 - Fetch matched files"
      ansible.builtin.fetch:
        src: "{{ complyctl_workdir }}/{{ item }}"
        dest: "{{ local_directories[1] }}/"
        flat: true
      become: true
      loop: "{{ phase2_files.results | map(attribute='stdout_lines') | flatten }}"

    - name: "Show output of tree commands to compare files before and after fixes"
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - result_tree_scan1.stdout_lines
        - result_tree_scan2.stdout_lines

    - name: "Now explore the fetched files in your local directories"
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ local_directories }}"
...
