---
- name: "Prepare the complyctl environment on the Demo VM"
  hosts: demo_vm
  become: false
  vars:
    # Update according to where https://github.com/complytime/complyctl.git was cloned
    complyctl_repo_dest: "~/GIT/ProdSec/complyctl"
    provider_dir: "~/.complytime/providers"

  tasks:
    - name: "Ensure removal of packages from previous installation"
      ansible.builtin.dnf:
        name:
          - complyctl
          - complyctl-openscap-plugin
        state: absent
      become: true

    - name: "Build complyctl locally"
      ansible.builtin.command:
        cmd: "make build"
        chdir: "{{ complyctl_repo_dest }}"
      delegate_to: localhost

    - name: "Ensure bin directory in home directory to make it easier to call complyctl"
      ansible.builtin.file:
        path: "~/bin"
        state: directory
        mode: "0750"

    - name: "Copy complyctl binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/complyctl"
        dest: "~/bin/complyctl"
        mode: "0750"

    - name: "Ensure providers directory exists"
      ansible.builtin.file:
        path: "{{ provider_dir }}"
        state: directory
        mode: "0750"

    - name: "Copy OpenSCAP provider binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/openscap-plugin"
        dest: "{{ provider_dir }}/complyctl-provider-openscap"
        mode: "0750"

    - name: "Copy mock-oci-registry binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/mock-oci-registry"
        dest: "~/bin/mock-oci-registry"
        mode: "0750"

    - name: "Copy AMPEL provider binary to Demo VM"
      ansible.builtin.copy:
        src: "{{ complyctl_repo_dest }}/bin/ampel-plugin"
        dest: "{{ provider_dir }}/complyctl-provider-ampel"
        mode: "0750"

    - name: "Install snappy tool"
      ansible.builtin.command:
        cmd: "go install github.com/carabiner-dev/snappy@latest"
      environment:
        GOPATH: "{{ ansible_env.HOME }}/go"

    - name: "Install ampel tool"
      ansible.builtin.command:
        cmd: "go install github.com/carabiner-dev/ampel/cmd/ampel@latest"
      environment:
        GOPATH: "{{ ansible_env.HOME }}/go"

    - name: "Ensure ~/go/bin is in PATH via .bashrc"
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$HOME/go/bin:$PATH"'
        regexp: 'export PATH="\$HOME/go/bin'
        state: present
...
